### ISSUE TITLE
The overview page takes too long to load (up to 10 seconds)

### ISSUE THREAD

**Issue by Sekuraz** [ternaris/marv#10]
Here is the marv log, we are using the config from the installation guide.

`/opt/bagbunker/venv/bin/uwsgi --ini /opt/bagbunker/site/uwsgi.conf
[uWSGI] getting INI configuration from /opt/bagbunker/site/uwsgi.conf
*** Starting uWSGI 2.0.14 (64bit) on [Thu Feb  2 13:21:23 2017] ***
compiled with version: 5.4.0 20160609 on 11 January 2017 16:02:12
os: Linux-4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016
nodename: ***********
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 12
current working directory: /opt/bagbunker
detected binary path: /opt/bagbunker/venv/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 257256
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:8000 fd 4
spawned uWSGI http 1 (pid: 30449)
uwsgi socket 0 bound to TCP address 127.0.0.1:39715 (port auto-assigned) fd 3
Python version: 2.7.12 (default, Nov 19 2016, 06:48:10)  [GCC 5.4.0 20160609]
Python main interpreter initialized at 0xf92780
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72768 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
2017-02-02 13:21:23,625 WARNING marv._site Unused config sections ['marv']
2017-02-02 13:21:23,627 DEBUG marv.app.listing init app
2017-02-02 13:21:23,664 INFO marv.app.listing listening on /opt/bagbunker/site/notify
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xf92780 pid: 30448 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 30448, cores: 1)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/bagbunker/venv/local/lib/python2.7/site-packages/marv/app/listing.py", line 157, in listen
    listener = Listener(self.site.socket, authkey=self.site.authkey)
  File "/usr/lib/python2.7/multiprocessing/connection.py", line 132, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/usr/lib/python2.7/multiprocessing/connection.py", line 256, in __init__
    self._socket.bind(address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

2017-02-02 13:21:23,684 INFO marv.app.listing Listing is up-to-date
2017-02-02 13:21:23,684 INFO marv.app.listing waiting for notification
[pid: 30448|app: 0|req: 1/1] 10.66.173.14 () {40 vars in 701 bytes} [Thu Feb  2 13:21:28 2017] GET / => generated 4366 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 81 bytes (1 switches on core 0)
[pid: 30448|app: 0|req: 2/2] 10.66.173.14 () {44 vars in 790 bytes} [Thu Feb  2 13:21:28 2017] GET /main-built.js => generated 0 bytes in 8 msecs (HTTP/1.1 304) 4 headers in 180 bytes (0 switches on core 0)
[pid: 30448|app: 0|req: 3/3] 10.66.173.14 () {44 vars in 807 bytes} [Thu Feb  2 13:21:28 2017] GET /main-built.css => generated 0 bytes in 2 msecs (HTTP/1.1 304) 4 headers in 180 bytes (0 switches on core 0)
[pid: 30448|app: 0|req: 4/4] 10.66.173.14 () {44 vars in 820 bytes} [Thu Feb  2 13:21:28 2017] GET /app/styles/ternaris-weiss.svg => generated 0 bytes in 2 msecs (HTTP/1.1 304) 4 headers in 178 bytes (0 switches on core 0)
[pid: 30448|app: 0|req: 5/5] 10.66.173.14 () {40 vars in 747 bytes} [Thu Feb  2 13:21:28 2017] GET /marv/api/2/login => generated 23 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 71 bytes (2 switches on core 0)
2017-02-02 13:21:36,837 DEBUG marv._detail Rendering <Keyval ['filesets', 'size', 'duration']>
2017-02-02 13:21:36,838 DEBUG marv._detail Rendering <Item 'filesets' ['rows']>
2017-02-02 13:21:36,838 DEBUG marv._aggregate extracting: 'len(rows)'
2017-02-02 13:21:36,838 DEBUG marv._detail Rendering <Item 'size' ['rows']>
2017-02-02 13:21:36,838 DEBUG marv._aggregate extracting: "sum(x['values'][1] or 0 for x in rows)"
2017-02-02 13:21:36,838 DEBUG marv._detail Rendering <Item 'duration' ['rows']>
2017-02-02 13:21:36,838 DEBUG marv._aggregate extracting: "sum(x['values'][-1] or 0 for x in rows)"
[pid: 30448|app: 0|req: 6/6] 10.66.173.14 () {40 vars in 768 bytes} [Thu Feb  2 13:21:28 2017] GET /marv/api/2/fileset-listing? => generated 502352 bytes in 8205 msecs (HTTP/1.1 200) 2 headers in 75 bytes (2 switches on core 0)
`

**Comment by Sekuraz** [comment]
Oh and I wonder where the exception comes from.

**Comment by NikolausDemmel** [comment]
Not sure if it is related to loading time, but looks like the exception is caused by a stale file `/opt/bagbunker/site/notify`. We had this (or a similar) exeception as well a while back after non-clean restarts of the server. We are now removing that file before every start if present. (See for example https://gist.github.com/NikolausDemmel/9248dcde78a4d725cda8cdee32ed67fe#file-marv_entrypoint-sh-L19)

**Comment by chaoflow** [comment]
Correct, the exception is socket that is not cleaned up, see also https://github.com/ternaris/marv-robotics/issues/11

**Comment by chaoflow** [comment]
This is solved in 17.11
