### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'set' and 'KeysView'

### ISSUE THREAD

**Issue by spmaniato** [ternaris/marv#12]
I'm playing around with `marv-robotics` (which I installed using `pip`'s `--pre` option) and keep getting the error below when I try to run any node (including `--all-nodes`). I'm posting about it here since the error is coming from `marv/cli.py`.

```shell
root@marv-robotics:/site# marv node run --all-filesets --node bagset_name

2017-03-03 21:48:59,821 INFO rospy.topics topicmanager initialized
2017-03-03 21:49:00,017 INFO marv._node Registered nodes in order: ['fileset', u'md5', u'bagset_name', u'bagmeta', u'messages', u'camera_frames', u'diag_count', u'fulltext', u'gnss_plots', u'navsatfix', u'geo_json_trajectory']
2017-03-03 21:49:00,020 WARNING marv._site Unused config sections ['marv']
Traceback (most recent call last):
  File "/usr/local/bin/marv", line 9, in <module>
    load_entry_point('marv-cli==2.0.0b2', 'console_scripts', 'marv')()
  File "/usr/local/lib/python2.7/dist-packages/marv_cli/__init__.py", line 48, in cli
    marv(auto_envvar_prefix='MARV')
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/marv/cli.py", line 248, in marv_node_run
    unknown = set(node) - app.site.nodes.nodes.viewkeys()
TypeError: unsupported operand type(s) for -: 'set' and 'KeysView'
2017-03-03 21:49:00,021 INFO rospy.core signal_shutdown [atexit]
```

I tried to reproduce the error in a Python interpreter, but could not:

```shell
root@marv-robotics:/site# python
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
```
```python
>>> d = {1: 'a'}
>>> d.viewkeys()
dict_keys([1])
>>> s = set([1, 2])
>>> s - d.viewkeys()
set([2])
```

Thanks :slightly_smiling_face: 

PS1. I should also note that I'm running all of this in a Docker container based on `ros:indigo-ros-base`
PS2. I also tried from within a `virtualenv` and without `--pre`. I still got the exact same error.

**Comment by NikolausDemmel** [comment]
Not sure if that related, but have you tried with a more recent version of python as suggested in the [Readme](https://github.com/ternaris/marv-robotics/blob/master/README.rst) (they recommend 2.7.12, e.g. from the PPA in the readme)?

**Comment by spmaniato** [comment]
@NikolausDemmel Wow, that worked! On the one hand, I'm glad it did. On the other hand, this PPA doesn't inspire confidence: https://launchpad.net/~fkrull/+archive/ubuntu/deadsnakes-python2.7 :stuck_out_tongue: I guess I'll just get Python `2.7.12` from elsewhere. Regardless, thanks a lot for the help :slightly_smiling_face:

**Comment by NikolausDemmel** [comment]
Sure, feel free to get it elsewise. 2.7.12 in the POA is at least the second to latest release and replaces your system python. You can always compile and use in a venv. Eg like this: http://mbless.de/blog/2016/01/09/upgrade-to-python-2711-on-ubuntu-1404-lts.html

Maybe you can report back what install method worked for you in the end.
