### ISSUE TITLE
installation of marv seems to fail due to pycapnp-for-marv

### ISSUE THREAD

**Issue by sebastianscherer** [ternaris/marv#16]
Hi,

the installation currently fails for us with the error message below. It seems to be a problem with pycapnp-for-marv.

`pip install marv-robotics`

results in 

```
Collecting marv-robotics
  Using cached marv_robotics-3.0.0-py2-none-any.whl
Collecting marv (from marv-robotics)
  Using cached marv-3.0.0-py2-none-any.whl Requirement already satisfied: matplotlib in /usr/lib/python2.7/dist-packages (from marv-robotics) Requirement already satisfied: pillow in /usr/lib/python2.7/dist-packages (from marv-robotics) Collecting utm (from marv-robotics) Requirement already satisfied: bcrypt in ./bagbunker/venv/lib/python2.7/site-packages (from marv->marv-robotics) Requirement already satisfied: Flask-SQLAlchemy in ./bagbunker/venv/lib/python2.7/site-packages (from marv->marv-robotics) Requirement already satisfied: Flask-Cors in ./bagbunker/venv/lib/python2.7/site-packages (from marv->marv-robotics) Requirement already satisfied: marv-cli in ./bagbunker/venv/lib/python2.7/site-packages (from marv->marv-robotics) Requirement already satisfied: PyJWT in ./bagbunker/venv/lib/python2.7/site-packages (from marv->marv-robotics) Requirement already satisfied: configparser in ./bagbunker/venv/lib/python2.7/site-packages (from marv->marv-robotics) Collecting pycapnp-for-marv (from marv->marv-robotics)
  Using cached pycapnp-for-marv-0.5.9.tar.gz Requirement already satisfied: cffi>=1.1 in ./bagbunker/venv/lib/python2.7/site-packages (from bcrypt->marv->marv-robotics) Requirement already satisfied: six>=1.4.1 in /usr/local/lib/python2.7/dist-packages (from bcrypt->marv->marv-robotics) Requirement already satisfied: SQLAlchemy>=0.8.0 in ./bagbunker/venv/lib/python2.7/site-packages (from Flask-SQLAlchemy->marv->marv-robotics)
Requirement already satisfied: Flask>=0.10 in ./bagbunker/venv/lib/python2.7/site-packages (from Flask-SQLAlchemy->marv->marv-robotics)
Requirement already satisfied: click in ./bagbunker/venv/lib/python2.7/site-packages (from marv-cli->marv->marv-robotics) Requirement already satisfied: pycparser in ./bagbunker/venv/lib/python2.7/site-packages (from cffi>=1.1->bcrypt->marv->marv-robotics)
Requirement already satisfied: itsdangerous>=0.21 in ./bagbunker/venv/lib/python2.7/site-packages (from Flask>=0.10->Flask-SQLAlchemy->marv->marv-robotics)
Requirement already satisfied: Werkzeug>=0.7 in ./bagbunker/venv/lib/python2.7/site-packages (from Flask>=0.10->Flask-SQLAlchemy->marv->marv-robotics)
Requirement already satisfied: Jinja2>=2.4 in /usr/lib/python2.7/dist-packages (from Flask>=0.10->Flask-SQLAlchemy->marv->marv-robotics)
Requirement already satisfied: MarkupSafe in /usr/lib/python2.7/dist-packages (from Jinja2>=2.4->Flask>=0.10->Flask-SQLAlchemy->marv->marv-robotics)
Building wheels for collected packages: pycapnp-for-marv
  Running setup.py bdist_wheel for pycapnp-for-marv ... error
  Complete output from command /opt/bagbunker/venv/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-It3_9q/pycapnp-for-marv/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpL6x65Kpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/capnp
  copying capnp/_gen.py -> build/lib.linux-x86_64-2.7/capnp
  copying capnp/version.py -> build/lib.linux-x86_64-2.7/capnp
  copying capnp/__init__.py -> build/lib.linux-x86_64-2.7/capnp
  copying capnp/__init__.pxd -> build/lib.linux-x86_64-2.7/capnp
  copying capnp/schema.capnp -> build/lib.linux-x86_64-2.7/capnp
  copying capnp/c++.capnp -> build/lib.linux-x86_64-2.7/capnp
  creating build/lib.linux-x86_64-2.7/capnp/helpers
  copying capnp/helpers/__init__.pxd -> build/lib.linux-x86_64-2.7/capnp/helpers
  copying capnp/helpers/helpers.pxd -> build/lib.linux-x86_64-2.7/capnp/helpers
  copying capnp/helpers/non_circular.pxd -> build/lib.linux-x86_64-2.7/capnp/helpers
  copying capnp/helpers/checkCompiler.h -> build/lib.linux-x86_64-2.7/capnp/helpers
  copying capnp/helpers/asyncHelper.h -> build/lib.linux-x86_64-2.7/capnp/helpers
  copying capnp/helpers/serialize.h -> build/lib.linux-x86_64-2.7/capnp/helpers
  copying capnp/helpers/fixMaybe.h -> build/lib.linux-x86_64-2.7/capnp/helpers
  copying capnp/helpers/rpcHelper.h -> build/lib.linux-x86_64-2.7/capnp/helpers
  copying capnp/helpers/capabilityHelper.h -> build/lib.linux-x86_64-2.7/capnp/helpers
  creating build/lib.linux-x86_64-2.7/capnp/includes
  copying capnp/includes/__init__.pxd -> build/lib.linux-x86_64-2.7/capnp/includes
  copying capnp/includes/types.pxd -> build/lib.linux-x86_64-2.7/capnp/includes
  copying capnp/includes/schema_cpp.pxd -> build/lib.linux-x86_64-2.7/capnp/includes
  copying capnp/includes/capnp_cpp.pxd -> build/lib.linux-x86_64-2.7/capnp/includes
  creating build/lib.linux-x86_64-2.7/capnp/lib
  copying capnp/lib/__init__.pxd -> build/lib.linux-x86_64-2.7/capnp/lib
  copying capnp/lib/capnp.pxd -> build/lib.linux-x86_64-2.7/capnp/lib
  copying capnp/lib/pickle_helper.py -> build/lib.linux-x86_64-2.7/capnp/lib
  copying capnp/lib/__init__.py -> build/lib.linux-x86_64-2.7/capnp/lib
  copying capnp/lib/capnp.pyx -> build/lib.linux-x86_64-2.7/capnp/lib
  creating build/lib.linux-x86_64-2.7/capnp/templates
  copying capnp/templates/setup.py.tmpl -> build/lib.linux-x86_64-2.7/capnp/templates
  copying capnp/templates/module.pyx -> build/lib.linux-x86_64-2.7/capnp/templates
  running build_ext
  creating /tmp/tmp2Uh5cv/tmp
  cc -c /tmp/timer_createxNM3E2.c -o /tmp/tmp2Uh5cv/tmp/timer_createxNM3E2.o
  /tmp/timer_createxNM3E2.c:1:1: warning: return type defaults to ‘int’ [-Wimplicit-int]
   main (int argc, char **argv) {
   ^
  /tmp/timer_createxNM3E2.c: In function ‘main’:
  /tmp/timer_createxNM3E2.c:2:5: warning: implicit declaration of function ‘timer_create’ [-Wimplicit-function-declaration]
       timer_create();
       ^
  cc /tmp/tmp2Uh5cv/tmp/timer_createxNM3E2.o -o /tmp/tmp2Uh5cv/a.out
  /tmp/tmp2Uh5cv/tmp/timer_createxNM3E2.o: In function `main':
  timer_createxNM3E2.c:(.text+0x15): undefined reference to `timer_create'
  collect2: error: ld returned 1 exit status
  creating tmp
  creating tmp/tmp2Uh5cv
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -c /tmp/tmp2Uh5cv/vers.cpp -o tmp/tmp2Uh5cv/vers.o --std=c++11
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  /tmp/tmp2Uh5cv/vers.cpp:4:26: fatal error: capnp/common.h: No such file or directory
  compilation terminated.
  *WARNING* no libcapnp detected. Will download and build it from source now. If you have C++ Cap'n Proto installed, it may be out of date or is not being detected. Downloading and building libcapnp may take a while.
  fetching https://capnproto.org/capnproto-c++-0.5.2.tar.gz into /tmp/pip-build-It3_9q/pycapnp-for-marv/bundled
  ar: `u' modifier ignored since `D' is the default (see `U')
  ar: `u' modifier ignored since `D' is the default (see `U')
  ar: `u' modifier ignored since `D' is the default (see `U')
  ar: `u' modifier ignored since `D' is the default (see `U')
  ar: `u' modifier ignored since `D' is the default (see `U')
  building 'capnp.lib.capnp' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/capnp
  creating build/temp.linux-x86_64-2.7/capnp/lib
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I. -I/usr/include/python2.7 -I/tmp/pip-build-It3_9q/pycapnp-for-marv/build/include -c capnp/lib/capnp.cpp -o build/temp.linux-x86_64-2.7/capnp/lib/capnp.o --std=c++11
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  capnp/lib/capnp.cpp:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
   #error Do not use this file, it is the result of a failed Cython compilation.
    ^
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pycapnp-for-marv
  Running setup.py clean for pycapnp-for-marv Failed to build pycapnp-for-marv Installing collected packages: pycapnp-for-marv, marv, utm, marv-robotics
  Running setup.py install for pycapnp-for-marv ... error
    Complete output from command /opt/bagbunker/venv/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-It3_9q/pycapnp-for-marv/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-Pn9tLg-record/install-record.txt --single-version-externally-managed --compile --install-headers /opt/bagbunker/venv/include/site/python2.7/pycapnp-for-marv:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-It3_9q/pycapnp-for-marv/setup.py", line 92, in <module>
        from Cython.Distutils import build_ext as build_ext_c
    ImportError: No module named Cython.Distutils
    
    ----------------------------------------
Command "/opt/bagbunker/venv/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-It3_9q/pycapnp-for-marv/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-Pn9tLg-record/install-record.txt --single-version-externally-managed --compile --install-headers /opt/bagbunker/venv/include/site/python2.7/pycapnp-for-marv" failed with error code 1 in /tmp/pip-build-It3_9q/pycapnp-for-marv/
```

**Comment by Heuvendw** [comment]
I'm having the same issue (timer, non-compiling), 
However I dont receive the missing capnp/common.h header error.
I think i fixed that one by installing the libcapnp-dev package.

Outcommenting the buildutils/detect.py check and adding the rt lib did remove the timer errors, however building still fails on the failed Cython line.

**Comment by beetleskin** [comment]
I got the very same issue, but it looks like it doesn't affect the installation ..?

**Comment by durko** [comment]
The error regarding `timer_create` hints a an outdated system libcapnp, in which case pycapnp tries to build a more recent version.

I would like to reproduce this error and need some information:
- What Linux distro are you using? Could you please paste the output of `cat /etc/os-release` here?
- What is the output of `python -c 'import Cython.Distutils'` and `pip list`?

**Comment by beetleskin** [comment]
I'm running marv from docker:
```Dockerfile
FROM ros:kinetic-ros-base

WORKDIR /srv/marv
ADD ./site /srv/marv/

EXPOSE 8000

# upate
RUN apt-get update

# install pre-requirements
RUN apt-get install -y \
    wget \
    capnproto \
    ffmpeg \
    libcapnp-dev \
    libjpeg-dev \
    libz-dev \
    python-cv-bridge \
    python2.7-dev \
    python-opencv \
    python-pip

# download and install marv requirements
RUN wget https://raw.githubusercontent.com/ternaris/marv-robotics/master/requirements.txt -P /tmp && \
    pip install -U pip setuptools pip-tools && \
    pip install -r /tmp/requirements.txt  && \
    rm /tmp/requirements.txt

# install marv
RUN pip install uwsgi marv-robotics

# .. more custom install stuff
```

```
root:/srv/marv/site# cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

`python -c 'import Cython.Distutils' `returns nothing

```
root:/srv/marv/site# pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
actionlib (1.11.11)
alabaster (0.7.10)
argh (0.26.2)
autonomos-marv-tools (0.2.1, /srv/marv/autonomos_marv_tools)
Babel (2.5.0)
backports.functools-lru-cache (1.4)
backports.shutil-get-terminal-size (1.0.0)
bcrypt (3.1.4)
bondpy (1.8.1)
bzr (2.7.0)
catkin (0.7.8)
catkin-pkg (0.3.9)
catkin-pkg-modules (0.3.9)
catkin-tools (0.4.4)
certifi (2017.7.27.1)
cffi (1.11.2)
chardet (3.0.4)
click (6.7)
configobj (5.0.6)
configparser (3.5.0)
coverage (4.4.1)
cycler (0.10.0)
Cython (0.26.1)
decorator (4.1.2)
defusedxml (0.4.1)
docutils (0.14)
dynamic-reconfigure (1.5.48)
ecdsa (0.13)
empy (3.3.2)
enum34 (1.1.6)
first (2.0.1)
flake8 (3.4.1)
Flask (0.12.2)
Flask-Cors (3.0.3)
Flask-SQLAlchemy (2.3.2)
funcsigs (1.0.2)
functools32 (3.2.3.post2)
futures (3.0.5)
gencpp (0.5.5)
geneus (2.2.6)
genlisp (0.4.16)
genmsg (0.5.9)
gennodejs (2.0.1)
genpy (0.6.7)
idna (2.6)
imagesize (0.7.1)
ipdb (0.10.3)
ipdbplugin (1.4.5)
ipython (5.4.1)
ipython-genutils (0.2.0)
itsdangerous (0.24)
Jinja2 (2.10)
MarkupSafe (1.0)
marv (3.0.0)
marv-cli (3.0.0)
marv-robotics (3.0.0)
matplotlib (2.1.1)
mccabe (0.6.1)
mercurial (3.7.3)
message-filters (1.12.12)
mock (2.0.0)
mpld3 (0.3)
netifaces (0.10.4)
nose (1.3.7)
numpy (1.14.0)
oauthlib (2.0.3)
olefile (0.44)
osrf-pycommon (0.1.4)
paramiko (1.16.0)
pathlib2 (2.3.0)
pathtools (0.1.2)
pbr (3.1.1)
pexpect (4.2.1)
pickleshare (0.7.4)
Pillow (5.0.0)
pip (9.0.1)
pip-tools (1.11.0)
pluginlib (1.11.2)
prompt-toolkit (1.0.15)
ptyprocess (0.5.2)
pycapnp-for-marv (0.5.9)
pycodestyle (2.3.1)
pycparser (2.18)
pycrypto (2.6.1)
pyflakes (1.5.0)
Pygments (2.2.0)
PyJWT (1.5.3)
pyparsing (2.2.0)
Pyste (0.9.10)
python-dateutil (2.6.1)
pytz (2017.3)
PyYAML (3.12)
requests (2.18.4)
requests-oauthlib (0.8.0)
roman (2.0.0)
rosbag (1.12.12)
rosboost-cfg (1.13.6)
rosclean (1.13.6)
roscreate (1.13.6)
rosdep (0.11.8)
rosdistro (0.6.2)
rosdistro-modules (0.6.2)
rosgraph (1.12.12)
rosinstall (0.7.8)
roslaunch (1.12.12)
roslib (1.13.6)
roslz4 (1.12.12)
rosmake (1.13.6)
rosmaster (1.12.12)
rosmsg (1.12.12)
rosnode (1.12.12)
rosparam (1.12.12)
rospkg (1.1.4)
rospkg-modules (1.1.4)
rospy (1.12.12)
rosservice (1.12.12)
rostest (1.12.12)
rostopic (1.12.12)
rosunit (1.13.6)
roswtf (1.12.12)
scandir (1.5)
sensor-msgs (1.12.5)
setuptools (38.2.5)
simplegeneric (0.8.1)
six (1.11.0)
smclib (1.8.1)
snowballstemmer (1.2.1)
Sphinx (1.6.3)
sphinx-paramlinks (0.3.4)
sphinxcontrib-websupport (1.0.1)
SQLAlchemy (1.2.0)
subprocess32 (3.2.7)
termcolor (1.1.0)
testfixtures (5.2.0)
topic-tools (1.12.12)
traitlets (4.3.2)
trollius (2.0.1)
typing (3.6.2)
urllib3 (1.22)
utm (0.4.2)
uWSGI (2.0.15)
vcstools (0.1.39)
watchdog (0.8.3)
wcwidth (0.1.7)
Werkzeug (0.14.1)
wheel (0.29.0)
wstool (0.1.13)
wxPython (3.0.2.0)
wxPython-common (3.0.2.0)
```

**Comment by durko** [comment]
@beetleskin In your case pycapnp is indeed being installed correctly, as Ubuntu 16.04 ships a recent libcapnp.

On second look: The `timer_create` error can safely be ignored, as it is part of a test that determines if librt has to be linked explicitly against.

@sebastianscherer @Heuvendw You seem to be affected by an additional real error. Could you please also post the above information?

**Comment by Heuvendw** [comment]
Docker image:
```
FROM tno/ros-bag-tools # local image
RUN apt-get update

RUN apt-get install -y curl \
            python-cv-bridge \
            python2.7-dev \
            python-opencv \
            python-virtualenv \
            libjpeg-dev \
            libz-dev\
            python-pip\
            cron            

RUN apt-get install -y libcapnp-dev capnproto

RUN pip install --upgrade pip

# install required packages
RUN pip install django==1.11.9
RUN pip install pip setuptools uwsgi serializer scipy image Cython

# Marv requirements
RUN wget https://raw.githubusercontent.com/ternaris/marv-robotics/master/requirements.txt -P /tmp && \
    pip install -U pip setuptools pip-tools && \
    pip install -r /tmp/requirements.txt  && \
    rm /tmp/requirements.txt

RUN pip install marv-robotics 
# Custom stuff
```
cat /etc/os-release
```
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
```
`RUN python -c 'import Cython.Distutils'` does not show any messages
RUN pip list
```
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
alabaster (0.7.10)
argh (0.26.2)
attrs (15.2.0)
autobahn (0.10.3)
Babel (2.5.0)
backports.shutil-get-terminal-size (1.0.0)
bcrypt (3.1.3)
bzr (2.7.0)
catkin-pkg (0.3.9)
catkin-pkg-modules (0.3.9)
certifi (2017.7.27.1)
cffi (1.10.0)
chardet (3.0.4)
click (6.7)
configobj (5.0.6)
configparser (3.5.0)
coverage (4.4.1)
cryptography (1.2.3)
cycler (0.10.0)
Cython (0.26.1)
decorator (4.1.2)
defusedxml (0.4.1)
Django (1.11.9)
docutils (0.14)
ecdsa (0.13)
empy (3.3.2)
enum34 (1.1.6)
first (2.0.1)
flake8 (3.4.1)
Flask (0.12.2)
Flask-Cors (3.0.3)
Flask-SQLAlchemy (2.2)
funcsigs (1.0.2)
functools32 (3.2.3.post2)
futures (3.0.5)
gcovr (3.2)
idna (2.6)
image (1.5.17)
imagesize (0.7.1)
ipaddress (1.0.16)
ipdb (0.10.3)
ipdbplugin (1.4.5)
ipython (5.4.1)
ipython-genutils (0.2.0)
itsdangerous (0.24)
Jinja2 (2.9.6)
lz4 (0.7.0)
MarkupSafe (1.0)
marv (3.0.0)
marv-cli (3.0.0)
marv-robotics (3.0.0)
matplotlib (2.0.2)
mccabe (0.6.1)
mercurial (3.7.3)
mock (2.0.0)
mpi4py (1.3.1)
mpld3 (0.3)
msgpack-python (0.4.6)
netifaces (0.10.4)
nose (1.3.7)
numpy (1.13.1)
oauthlib (2.0.3)
olefile (0.44)
PAM (0.4.2)
paramiko (1.16.0)
pathlib2 (2.3.0)
pathtools (0.1.2)
pbr (3.1.1)
pexpect (4.2.1)
pickleshare (0.7.4)
Pillow (4.2.1)
pip (9.0.1)
pip-tools (1.11.0)
prompt-toolkit (1.0.15)
psutil (3.4.2)
ptyprocess (0.5.2)
pyasn1 (0.1.9)
pyasn1-modules (0.0.7)
pycapnp-for-marv (0.5.9)
pycodestyle (2.3.1)
pycparser (2.18)
pycrypto (2.6.1)
pydot (1.0.29)
pyflakes (1.5.0)
Pygments (2.2.0)
pygraphviz (1.3.1)
PyJWT (1.5.3)
PyOpenGL (3.0.2)
pyOpenSSL (0.15.1)
pyparsing (2.2.0)
pyserial (3.0.1)
Pyste (0.9.10)
python-dateutil (2.6.1)
python-snappy (0.5)
pytz (2017.2)
PyYAML (3.12)
requests (2.18.4)
requests-oauthlib (0.8.0)
roman (2.0.0)
rosdep (0.11.8)
rosdistro (0.6.2)
rosdistro-modules (0.6.2)
rosinstall (0.7.8)
rospkg (1.1.4)
rospkg-modules (1.1.4)
scandir (1.5)
scipy (0.17.0)
Serializer (0.2.1)
service-identity (16.0.0)
setuptools (38.4.0)
simplegeneric (0.8.1)
simplejson (3.13.2)
six (1.10.0)
snowballstemmer (1.2.1)
Sphinx (1.6.3)
sphinx-paramlinks (0.3.4)
sphinxcontrib-websupport (1.0.1)
SQLAlchemy (1.1.14)
subprocess32 (3.2.7)
termcolor (1.1.0)
testfixtures (5.2.0)
traitlets (4.3.2)
trollius (2.0.1)
Twisted (16.0.0)
txaio (1.0.0)
typing (3.6.2)
urllib3 (1.22)
utm (0.4.2)
uWSGI (2.0.15)
vcstools (0.1.39)
virtualenv (15.0.1)
watchdog (0.8.3)
wcwidth (0.1.7)
Werkzeug (0.12.2)
wheel (0.29.0)
wstool (0.1.13)
wxPython (3.0.2.0)
wxPython-common (3.0.2.0)
zope.interface (4.1.3)
```

The installation does finish with the this dockerfile, however I still see this message at the end of the installation:
```
  Failed building wheel for pycapnp-for-marv
  Running setup.py clean for pycapnp-for-marv
Failed to build pycapnp-for-marv
Installing collected packages: marv-cli, pycapnp-for-marv, marv, marv-robotics
  Running setup.py install for pycapnp-for-marv: started
    Running setup.py install for pycapnp-for-marv: finished with status 'done'
Successfully installed marv-3.0.0 marv-cli-3.0.0 marv-robotics-3.0.0 pycapnp-for-marv-0.5.9
```

**Comment by durko** [comment]
@Heuvendw your installation should be fine. The output of the pycapnp build phase is really confusing, as all occurring errors are non fatal. As long as the exit code of pip install is zero installation seems to be ok so far.

**Comment by chaoflow** [comment]
@Heuvendw @sebastianscherer can you confirm, that marv actually works for you, despite pycapnp-for-marv complaining about alleged errors?

**Comment by sebastianscherer** [comment]
Hi,

if I manually install the following dependencies before marv, marv will start despite the pycapnp-for-marv error:

> pip install requests_oauthlib cython

I guess these dependencies should be added to setup.py?

Best,
Sebastian

**Comment by Heuvendw** [comment]
@chaoflow I can confirm marv appears to work properly for my setup. (the wheel error is only shown during building of the docker file)

**Comment by chaoflow** [comment]
@Heuvendw thx!

@sebastianscherer Could you please double-check that you installed the requirements with ``pip-sync`` and activated the virtual environment, see:
- https://ternaris.com/marv-robotics/docs/install.html#prerequisites
- https://ternaris.com/marv-robotics/docs/install.html#install-requirements
- https://github.com/ternaris/marv-robotics/blob/master/requirements.txt
What is the output of:
- ``which python`` and
- ``pip list``

**Comment by chaoflow** [comment]
With upgrading to latest pycapnp these error message are gone.
