### ISSUE TITLE
Cryptic errors on custom node

### ISSUE THREAD

**Issue by beetleskin** [ternaris/marv#17]
Hi, I wrote a very basic custom node extracting a standard string message and returning the content of it as Tag. I added this tag to the config such that it is shown as column in the list-overview of all bags. 
When I run the node with `marv run --collection=bag`, I get the following error:
```
2018-01-02 21:04:46,043 ERRO marv.cli Exception occured for dataset 6ajyufanbn24imcj23bto3ves4:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/marv/cli.py", line 390, in marvcli_run
    cachesize=cachesize)
  File "/usr/local/lib/python2.7/dist-packages/marv/site.py", line 355, in run
    deps=deps, cachesize=cachesize)
  File "/usr/local/lib/python2.7/dist-packages/marv_node/run.py", line 75, in run_nodes
    done, send_queue_empty = process_task(current, task)
  File "/usr/local/lib/python2.7/dist-packages/marv_node/run.py", line 375, in process_task
    return loop()
  File "/usr/local/lib/python2.7/dist-packages/marv_node/run.py", line 254, in loop
    promise = current.send(send)
  File "/usr/local/lib/python2.7/dist-packages/marv_node/driver.py", line 242, in _run
    assert stream.handle not in self.streams, stream
AssertionError: <VolatileStream 6ajyufanbn.raw_messages.gahvdc4vpg./carstate/vehicle_name>
2018-01-02 21:04:46,044 ERRO marv.cli Error occured for dataset 6ajyufanbn24imcj23bto3ves4: <VolatileStream 6ajyufanbn.raw_messages.gahvdc4vpg./carstate/vehicle_name>
```

Strangely, when I run the node explicitly afterwards (with `--node my_node`), I don't get any errors. When I then run all nodes again, also no error occurs. However, the frontend then is not rendered accoding to the config, the extracted data from my custom node is missing. The whole problem is even weirder, if I use the `-f` option, which triggers the error again, but only if I don't run the node explicitly.

---

Another cryptic error is:
```
2018-01-02 23:15:39,098 ERRO marv.cli Exception occured for dataset ga6pucf2rfuud7qq6mkizgvqke:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/marv/cli.py", line 390, in marvcli_run
    cachesize=cachesize)
  File "/usr/local/lib/python2.7/dist-packages/marv/site.py", line 355, in run
    deps=deps, cachesize=cachesize)
  File "/usr/local/lib/python2.7/dist-packages/marv_node/run.py", line 75, in run_nodes
    done, send_queue_empty = process_task(current, task)
  File "/usr/local/lib/python2.7/dist-packages/marv_node/run.py", line 316, in process_task
    stream.add_msg(msg)
  File "/usr/local/lib/python2.7/dist-packages/marv_store/streams.py", line 131, in add_msg
    assert msg.data is THEEND
AssertionError
2018-01-02 23:15:39,099 ERRO marv.cli Error occured for dataset ga6pucf2rfuud7qq6mkizgvqke:
```

.. this guy comes from triggering a custom node with custom "plain python" return type (decorator: `@marv.node()`). Apparently `msg.data` has no attr "_reader" since it is just what I pushed with `marv.push({..})`. So, there is something wrong in my node-graph?
  
  **Update**
I got this one. You raise this guy, if you create a node without capnp type (plain python return type?), but list the node in the marv config. I conclude: all nodes used in the config must push/return a capnp type. Without capnp type, you can only use the node "internally" as input to other nodes. Also, its output will not be cached, i.e. the node is run again if you re-run upstream nodes. This behavior/restriction was not clear to me.

**Comment by chaoflow** [comment]
@beetleskin thanks for your report! Could you provide a minimal working example (config and code) that triggers this bug?

**Comment by beetleskin** [comment]
The VolatileStream AssertionError is generated when running something like this:
```python
@marv.node(Tag)
@marv.input('stream', default=marv.select(raw_messages, "/my/string/topic/with/only/one/message"))
def single_string_node(stream):
    yield marv.set_header(title="my_fancy_stream_title")
    proto_msg = yield marv.pull(stream)
    assert proto_msg is not None
    rosmsg.deserialize(proto_msg.data)
    my_tag = rosmsg.data
    yield marv.push({'text': my_tag})
```

.. but as stated above, it only occurs when running all nodes after a fresh init/scan

**Comment by chaoflow** [comment]
@beetleskin thanks a lot! From where is ``Tag`` coming? I assume the ``single_string_node`` is also listed under the ``nodes`` key?

**Comment by beetleskin** [comment]
Tag comes from `from marv_nodes.types_capnp import Tag` and yes, the node is listed in the conf.

**Comment by chaoflow** [comment]
@beetleskin just saw your update to the initial comment. Is it correct, that all errors here are due to a node without type listed in the config file?

**Comment by beetleskin** [comment]
Sorry, I should not have created an issue with two errors (at first, they always occurred together, but  they're isolated issues).

But no, the _VolatileStream AssertionError_ occurs for the _single_string_node_, which is typed (Tag) and listed in the config.

**Comment by beetleskin** [comment]
Update (VolatileStream AssertionError): when I uncomment your `fulltext` node from the config, the error disappears. 

Diving a bit into the error, resp. the failing assertion, reveals that the node is "loaded" (?) twice into the driver? Due to `fulltext` pointing to the same input topic?

**Comment by chaoflow** [comment]
@beetleskin The first error was due to a bug which has been fixed, the second one is now properly caught and reported as configuration error, and the purpose of set_header is now [documented](https://ternaris.com/marv-robotics/docs/patterns.html#set-header)
