### ISSUE TITLE
Section 'Add and run basic nodes' in tutorial is broken.

### ISSUE THREAD

**Issue by solosuper** [ternaris/marv#42]
Hi,

I am following the tutorial and have come as far as https://ternaris.com/marv-robotics/docs/tutorial/setup-basic-site.html#add-and-run-basic-nodes

I have create a directory `site` and pasted the updated contents in `site/marv.conf`

```
[marv]
collections = bags

[collection bags]
scanner = marv_robotics.bag:scan
scanroots =
    ../scanroot

nodes =
    marv_nodes:dataset
    marv_robotics.bag:bagmeta
    marv_robotics.detail:bagmeta_table
    marv_robotics.detail:topics_section

detail_summary_widgets =
    bagmeta_table

detail_sections =
    topics_section
```

In the next step, `marv run --collection=bags` I get the following output:    
(PS. I have obfuscated my path before pasting)

```
INFO rospy.topics topicmanager initialized
ERRO marv.cli Exception occured for dataset pmaybq22sbaty45qrdtpgnqmfy:
Traceback (most recent call last):
  File "(...)/marv-tmp/venv/local/lib/python2.7/site-packages/marv/cli.py", line 418, in marvcli_run
    excluded_nodes, cachesize=cachesize)
  File "(...)/marv-tmp/venv/local/lib/python2.7/site-packages/marv/site.py", line 339, in run
    persistent = collection.nodes
  File "(...)/marv-tmp/venv/local/lib/python2.7/site-packages/marv/collection.py", line 177, in cached_func
    value = func(self)
  File "(...)/marv-tmp/venv/local/lib/python2.7/site-packages/marv/collection.py", line 264, in nodes
    raise ConfigError(self.section, 'nodes', 'Cannot find node %s' % line)
ConfigError: (...)/marv-tmp/site/marv.conf [collection bags] nodes: Cannot find node marv_robotics.detail:topics_section
ERRO marv.cli Error occured for dataset pmaybq22sbaty45qrdtpgnqmfy: (...)/marv-tmp/site/marv.conf [collection bags] nodes: Cannot find node marv_robotics.detail:topics_section
```

If I try `marv init` I get the following output:

```
INFO rospy.topics topicmanager initialized
Traceback (most recent call last):
  File "(...)/marv-tmp/venv/bin/marv", line 11, in <module>
    sys.exit(cli())
  File "(...)/marv-tmp/venv/local/lib/python2.7/site-packages/marv_cli/__init__.py", line 131, in cli
    marv(auto_envvar_prefix='MARV')
  File "(...)/marv-tmp/venv/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "(...)/marv-tmp/venv/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "(...)/marv-tmp/venv/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "(...)/marv-tmp/venv/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "(...)/marv-tmp/venv/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "(...)/marv-tmp/venv/local/lib/python2.7/site-packages/marv/cli.py", line 256, in marvcli_init
    create_app(init=True)
  File "(...)/marv-tmp/venv/local/lib/python2.7/site-packages/marv/cli.py", line 74, in create_app
    site.init()
  File "(...)/marv-tmp/venv/local/lib/python2.7/site-packages/marv/site.py", line 211, in init
    collection.render_detail(dataset)
  File "(...)/marv-tmp/venv/local/lib/python2.7/site-packages/marv/collection.py", line 625, in render_detail
    store = Store(storedir, self.nodes)
  File "(...)/marv-tmp/venv/local/lib/python2.7/site-packages/marv/collection.py", line 177, in cached_func
    value = func(self)
  File "(...)/marv-tmp/venv/local/lib/python2.7/site-packages/marv/collection.py", line 264, in nodes
    raise ConfigError(self.section, 'nodes', 'Cannot find node %s' % line)
marv.config.ConfigError: (...)/marv-tmp/site/marv.conf [collection bags] nodes: Cannot find node marv_robotics.detail:topics_section
```

Equivalent output with `marv scan`.

**Comment by solosuper** [comment]
Replacing `topics_section` with `connections_section` seems to be the fix, as that node has been renamed and updated between versions 17.11 and 18.02.

The config file now looks like
```
[marv]
collections = bags

[collection bags]
scanner = marv_robotics.bag:scan
scanroots =
    ../scanroot

nodes =
    marv_nodes:dataset
    marv_robotics.bag:bagmeta
    marv_robotics.detail:bagmeta_table
    marv_robotics.detail:connections_section

detail_summary_widgets =
    bagmeta_table

detail_sections =
    connections_section
```

https://github.com/ternaris/marv-robotics/commits/master/marv_robotics/detail.py

**Comment by chaoflow** [comment]
@solosuper thank you for pointing this out. Fix is in upcoming release.
